# Generated by Django 3.2.4 on 2021-06-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_site', models.CharField(blank=True, max_length=30)),
                ('eng_title', models.CharField(blank=True, max_length=200)),
                ('eng_sub_title', models.CharField(blank=True, max_length=200)),
                ('eng_content', models.CharField(blank=True, max_length=1000)),
                ('ko_title', models.CharField(blank=True, max_length=200)),
                ('ko_sub_title', models.CharField(blank=True, max_length=200)),
                ('ko_content', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
