# Generated by Django 3.2.4 on 2021-06-21 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlingdata',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='eng_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='eng_sub_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='eng_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='ko_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='ko_sub_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='ko_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='crawlingdata',
            name='news_site',
            field=models.CharField(default='', max_length=50),
        ),
    ]
